name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v6.3.0
        with:
          node-version-file: package.json
          check-latest: true
          cache: npm

      - name: Install JavaScript dependencies
        run: npm ci
